# Deep Learning Models
models:
  vehicle_model: "yolov8s.pt"
  traffic_light_model: "src/models/traffic_light_best.pt"

# Detection Thresholds
thresholds:
  vehicle_conf: 0.25
  traffic_light_conf: 0.05
  iou: 0.45

# Tracking Configuration (ByteTrack)
tracking:
  tracker_type: "bytetrack"
  conf: 0.1
  iou: 0.5
  track_buffer: 60

# Traffic Scene Parameters
scene:
  stop_line: [500, 495, 1080, 495]
  movement_direction: "down"
  
  # Polygon hình thang cho phép rẽ phải khi đèn đỏ (rộng trên, hẹp dưới)
  right_turn_zone: [[950, 200], [1200, 200], [1100, 495], [1080, 495]]
  
  # Cho phép YOLOv8 tự động phát hiện đèn ở BẤT KỲ vị trí nào trong khung hình
  traffic_light_roi: []
  
  # Đã xóa tọa độ cố định để AI tự động dò tìm hộp đèn động theo thời gian thực
  static_traffic_lights: [[1196, 58, 1234, 160]]

# Output Configurations
output:
  save_video: true
  output_video_path: "data/output/result_video.mp4"
  save_logs: true
  json_log_path: "data/output/violations.json"
  webhook_url: ""